// <auto-generated />
using Caching_Example.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Caching_Example.Migrations
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20231121105253_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Caching_Example.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            FirstName = "John",
                            LastName = "Doe",
                            UserName = "john_doe"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            FirstName = "Jane",
                            LastName = "Smith",
                            UserName = "jane_smith"
                        },
                        new
                        {
                            Id = 3,
                            Age = 35,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            UserName = "bob_johnson"
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            FirstName = "Alice",
                            LastName = "Williams",
                            UserName = "alice_williams"
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            UserName = "charlie_brown"
                        },
                        new
                        {
                            Id = 6,
                            Age = 23,
                            FirstName = "Eva",
                            LastName = "Davis",
                            UserName = "eva_davis"
                        },
                        new
                        {
                            Id = 7,
                            Age = 40,
                            FirstName = "Frank",
                            LastName = "Miller",
                            UserName = "frank_miller"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            FirstName = "Grace",
                            LastName = "Moore",
                            UserName = "grace_moore"
                        },
                        new
                        {
                            Id = 9,
                            Age = 33,
                            FirstName = "Harry",
                            LastName = "Clark",
                            UserName = "harry_clark"
                        },
                        new
                        {
                            Id = 10,
                            Age = 29,
                            FirstName = "Ivy",
                            LastName = "Turner",
                            UserName = "ivy_turner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
